version: "3.8"

services:
  postgres_asset_managment_server:
    container_name: postgres_asset_managment_server
    build: 
      dockerfile: Dockerfile.Postgres
    env_file:
      .env.dev
    ports:
      - "$POSTGRES_PORT:5432"
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - postgres_asset_managment_data:/var/lib/postgresql/data
    networks:
      - app_network
  asset_management:
    container_name: asset_management_service
    build:
      context: ./
      target: development
    restart: always
    env_file:
      .env.dev
    ports: 
      - "$PORT:9000"
    depends_on: 
     - postgres_asset_managment_server
    volumes:
      - ./:/app
      - ./log:/app/log
    environment:
      - NODE_ENV=development
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
volumes:
  postgres_asset_managment_data: